server:
  port: 7001

spring:
  # 数据库配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mind?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 111111
    #初始化连接数量
    initialSize: 10
    #最大连接数量
    maxActive: 20
    #最小空闲连接
    minIdle: 1
    #超时等待时间以毫秒为单位
    maxWait: 60000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    timeBetweenEvictionRunsMillis: 3600000
    minEvictableIdleTimeMillis: 300000
    #SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前
    validationQuery: SELECT 1 FROM DUAL
    #指明连接是否被空闲连接回收器(如果有)进行检验.
    #如果检测失败,则连接将被从池中去除.
    testWhileIdle: true
    #指明是否在从池中取出连接前进行检验,如果检验失败,
    #则从池中去除连接并尝试取出另一个.
    testOnBorrow: false
    #指明是否在归还到池中前进行检验
    testOnReturn: false
  # redis配置
  redis:
    timeout: 60000
    pool:
      max-active: 300
      max-wait: -1
      max-idle: 100
      min-idle: 20
    cluster:
      nodes: 192.169.11.11:7001,192.169.11.11:7002,192.169.11.11:7003

# mybatis-plus插件配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 分页插件
pagehelper:
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true

# 缓存配置
cacheConfig:
  # 启动redis,启用true，缓存使用redis，但需要配置redis相关地址，如果不使用默认使用ehcache缓存
  enableRedis: false